language: node_js
python:
- '3.6'
node_js:
- 8.11.3
before_install:
- export TZ=Asia/Taipei
install:
- yarn
script:
- git clone --depth 1 --branch gh-pages https://$GH_TOKEN@github.com/Panepo/PileBunker-ts
  build
- yarn parser
- yarn test && codecov
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: build
  on:
    branch: master
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
  - secure: cKidEbJ9Py5OP2EmFJ7xo4RL7jVIjb4FJw+ENcFjjtX3z98iPwA/YIMuTuGF95t+C7EymUnXb7Oh8q6OT06FlIxuZuwXJWRkKB7aztgf6dZiuSb8bzouh5GRZfH98pi4AoXkb1AMbo/w+Q7C0wWoh3CVFtZH45MUtX5VORQu01xqGaJ035iEANMJ7QRtpcNIuAjD4eY4l7Al1lL27Aj0YHziMAzlZUT+n8oM2lvkrJn/U5uinBGYDo3LMTwpiloXleMqcNZz6HKqHZ4bODwTMuwbhmW2ZcaMAubGr57ElAqUSqE8PIlJzruZOmPoKyHc0/72XiVAqnX3nF9lJfmWklG1gXmvU9zp7FxdtEesvYYPz9MleN5ueOq7n3Z1hKwr67RMvnYdF/XTRCP4suD/iEAue1QduIZeg/zvLMMRBMQdo/rNmi+24Zy4GdhOz6v1HpNo1MVqPhy6upe2KcMm7V70igwP+ca6eqsKl4vaRg7RBqdL8+SBBYmA2e+bOa3Y39iF4NLZy5fVfAjW57DqCJ2NS9e1LsCsPDFQ8eCKRGi7b96aWqb7UbkkYh3WSYzWUoiiwn8CuCa1qw0fC6lYR0c6j2LwDsST9thj3uHmanlCL5luo2lFxypCb7jIL7jhRKmY5pFyGnK3v0OqRuF/3k3Nsvq7RrV9IxWUXIqFTvc=
